/**
 *
 * @author Kuric
 */
//prieks datubazes savienosanas un darbam
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JTextField;
//Prieks panelu izvadisanam un citam
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.*;
public class Admin_page extends javax.swing.JFrame {
    Main_menu menu = null;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Admin admin;
    log_fails_page log_page;
    Login_page log;
    konts_infa k;
    statistic_show stata;
    Konti k1;
    /**
     * Creates new form Admin_page
     */
    public Admin_page() {
        initComponents();
        showTableData();
        jLabel1.setVisible(false);
    }
    


    public Admin_page(String id,String Vards ,Main_menu menu) {
        initComponents();
        jLabel7.setText("Labdien dargais admin "+Vards+", id= ");
        jLabel1.setText(id);
        this.menu = menu;
        this.setLocationRelativeTo(null);
        showTableData();
    }
    
    public Admin_page(String id){
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonexit_admin = new javax.swing.JButton();
        jTextField_id_add = new javax.swing.JTextField();
        jTextField_name_add = new javax.swing.JTextField();
        jTextField_surname_add = new javax.swing.JTextField();
        jTextField_email_add = new javax.swing.JTextField();
        jTextField_pass_add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_add_user = new javax.swing.JButton();
        jButton_update_user = new javax.swing.JButton();
        jButton_delete_user = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_add_credit_kont = new javax.swing.JButton();
        jButton_add_noguldijuma_konts = new javax.swing.JButton();
        jButton_log_file = new javax.swing.JButton();
        jButton_kont_infa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_statistic_show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonexit_admin.setText("Iziet");
        jButtonexit_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexit_adminActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Ievadiet ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Ievadiet vardu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ievadiet uzvardu");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Ievadiet E-pastu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ievadiet paroli");

        jButton_add_user.setText("Pievienot lietotaju");
        jButton_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_userActionPerformed(evt);
            }
        });

        jButton_update_user.setText("Mainit datus");
        jButton_update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_userActionPerformed(evt);
            }
        });

        jButton_delete_user.setText("Dzest lieitotaju");
        jButton_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_userActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Admin Page");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jButton_add_credit_kont.setText("Pievienot kredita kontu");
        jButton_add_credit_kont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_credit_kontActionPerformed(evt);
            }
        });

        jButton_add_noguldijuma_konts.setText("Pievienot noguldijuma kontu");
        jButton_add_noguldijuma_konts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_noguldijuma_kontsActionPerformed(evt);
            }
        });

        jButton_log_file.setText("Paskatities log failu useram(adminam )");
        jButton_log_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_log_fileActionPerformed(evt);
            }
        });

        jButton_kont_infa.setText("Paskatities kontus lietotajam");
        jButton_kont_infa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kont_infaActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_statistic_show.setText("Paskatities statistiku");
        jButton_statistic_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_statistic_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_id_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jTextField_name_add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_surname_add)
                            .addComponent(jTextField_email_add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_pass_add, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_add_noguldijuma_konts, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonexit_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_statistic_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_update_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_log_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_add_credit_kont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_kont_infa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_name_add)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_surname_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_email_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_pass_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_delete_user)
                            .addComponent(jButton_update_user)
                            .addComponent(jButton_add_user))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_add_credit_kont, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_add_noguldijuma_konts)))
                    .addComponent(jButton_statistic_show, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_kont_infa)
                        .addComponent(jButton_log_file))
                    .addComponent(jButtonexit_admin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonexit_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexit_adminActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        if (menu != null)
            menu.setVisible(true);
        
          try{
                String id =jLabel1.getText();
                String timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                String apraksts = "Admins ar id: "+id+" izgaja no sistemas: "+timeStamp;
                con = Connections_database.getConnection();
                java.sql.PreparedStatement stmt = con.prepareStatement(
                "INSERT INTO `log_file`(`ID`, `Apraksts`) VALUES (?,?)");
                stmt.setInt(1,Integer.parseInt(id));
                stmt.setString(2, apraksts);
                stmt.executeUpdate();
            }catch(Exception ex){
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_jButtonexit_adminActionPerformed

    private void jButton_update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_userActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        int returnn=0;
        String id = jTextField_id_add.getText();
        String name = jTextField_name_add.getText();
        String surname = jTextField_surname_add.getText();
        String email = jTextField_email_add.getText();
        String password = jTextField_pass_add.getText();
        if(id.equals("")){
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs,ludzu ievadiet lietotaja id!", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
            if(!password.equals("")){
            if(password.length()>8 || password.length()<=3){
                 JOptionPane.showMessageDialog(null, "Ievadita parole ir par mazu vai par lielu");
                 jTextField_pass_add.setText("");
                 returnn=1;
            }
            }
                if(!email.equals("")){
                if(!admin.check_email(email)){
                    JOptionPane.showMessageDialog(null, "Nepareizs e-mail,ludzu izmainiet to!");
                    jTextField_email_add.setText("");
                    returnn=1;
                }
                }
                
                if(!name.equals("")){
                    if(!admin.check_name(name)){
                        JOptionPane.showMessageDialog(null, "Nepareizs vards lietotajam,ludzu izmainiet to!");
                        jTextField_name_add.setText("");
                        returnn=1;
                }
                }
                    if(!surname.equals("")){
                    if(!admin.check_name(surname)){
                            JOptionPane.showMessageDialog(null, "Nepareizs uzvards lietotajam,ludzu izmainiet to!");
                            jTextField_surname_add.setText("");
                            returnn=1;
                    }
                    }
                        if(returnn==1){
                            JOptionPane.showMessageDialog(null, "Kaut kas jums nav pareizs,ludzu izlabojiet to!");
                        }else{
                            try{
 String sql = "UPDATE `useri` SET `ID`=?,`Vards`=?,`Uzvards`=?,`E_pasts`=?,`Parole`=?,`Conditions`='User' WHERE ID=? AND `Conditions`='User'";
 pst = con.prepareStatement(sql);

    pst.setString(5, password);



     pst.setString(4, email);


     pst.setString(2, name);

 

     pst.setString(3, surname);

pst.setString(1, id);
pst.setString(6, id);

 pst.executeUpdate();
 JOptionPane.showMessageDialog(null, "updated successfully");
  
 }
 catch(SQLException | HeadlessException ex){
 JOptionPane.showMessageDialog(null, ex);
 }
      showTableData();
                            jTextField_name_add.setText("");
                            jTextField_surname_add.setText("");
                            jTextField_email_add.setText("");
                            jTextField_pass_add.setText("");
                            jTextField_id_add.setText("");
                            JOptionPane.showMessageDialog(null, "Lietotajs tika izlabots,izmainas ir saglabatas!");
                        }            
        }
        
        
    }//GEN-LAST:event_jButton_update_userActionPerformed

    private void jButton_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_userActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        Konti k1 = new Konti();
        String id = jTextField_id_add.getText();
        String name = jTextField_name_add.getText();
        String surname = jTextField_surname_add.getText();
        String email = jTextField_email_add.getText();
        String password = jTextField_pass_add.getText();
        if(name.equals("") || surname.equals("") || email.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Kaut kadi lauki nav aizpilditi mes nevaram pievienot lietotaju!", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
            if(password.length()>8 || password.length()<=3){
                 JOptionPane.showMessageDialog(null, "Ievadita parole ir par mazu vai par lielu");
                 jTextField_pass_add.setText("");
            }else{
                if(!admin.check_email(email)){
                    JOptionPane.showMessageDialog(null, "Nepareizs e-mail,ludzu izmainiet to!");
                    jTextField_email_add.setText("");
                }else{
                    if(!admin.check_name(name)){
                        JOptionPane.showMessageDialog(null, "Nepareizs vards lietotajam,ludzu izmainiet to!");
                        jTextField_name_add.setText("");
                    }else{
                        if(!admin.check_name(surname)){
                            JOptionPane.showMessageDialog(null, "Nepareizs uzvards lietotajam,ludzu izmainiet to!");
                            jTextField_surname_add.setText("");
                        }else{
                            
                            name = admin.string_Upercase_name(name);
                            surname =admin.string_Upercase_surname(surname);
                            admin.addNewUser(name, surname, email, password);
                            showTableData();
                            jTextField_name_add.setText("");
                            jTextField_surname_add.setText("");
                            jTextField_email_add.setText("");
                            jTextField_pass_add.setText("");
                            JOptionPane.showMessageDialog(null, "Lietotajs tika izveidots un ierakstits datubaze!");
                            String number = null;
                            String condition = "Algas";
                            String number1 =k1.create_kont_number(number);
                            System.out.println(number1);
                            int summa= 0;
                            String timeStamp = null;
                            String apraksts = null;
                            Integer.toString(summa);
                            System.out.println(summa);
                            JOptionPane.showMessageDialog(null, "Algas Konts tika automatiski izveidots!");
                            k1.create_salary_kont(id, number1, summa);
                            timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                            apraksts = "Lietotajs ar id: "+id+" izveidoja algas kontu: "+timeStamp;
                            k1.log_konti(id, apraksts);
                        }
                    }
                }
            }
            
        }
    }//GEN-LAST:event_jButton_add_userActionPerformed

    private void jButton_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_userActionPerformed
        // TODO add your handling code here:
    Admin admin = new Admin(); 
    String id = jTextField_id_add.getText(); 
        if(id.equals("")){ 
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs!"); 
        }else{ 
           
            JOptionPane.showMessageDialog(null, id); 
            if(admin.check_Information_about_user(id)){ 
                    admin.deleteUser(id); 
                    admin.deleteKonts(id);
                    admin.deletelog(id);
                    showTableData(); 
                    JOptionPane.showMessageDialog(null, "Lietotajs ir veiksmigi izdzests"); 
                }else{ 
                    JOptionPane.showMessageDialog(null, "Lietotaja ar tadu id nav!"); 
                } 
            } 
    }//GEN-LAST:event_jButton_delete_userActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    int i=jTable1.getSelectedRow(); 
    TableModel model=jTable1.getModel(); 
    jTextField_id_add.setText(model.getValueAt(i,0).toString()); 
    jTextField_name_add.setText(model.getValueAt(i,1).toString()); 
    jTextField_surname_add.setText(model.getValueAt(i,2).toString()); 
    jTextField_email_add.setText(model.getValueAt(i,3).toString()); 
    jTextField_pass_add.setText(model.getValueAt(i,4).toString()); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_log_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_log_fileActionPerformed
        // TODO add your handling code here:
        log_fails_page log_page = new log_fails_page(this);
        String id = jTextField_id_add.getText();
        if(id.equals("")){ 
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs!");
        }else{
            log_page.setVisible(true);
            setVisible(false);
            Connections_database con = new Connections_database();
            log_page.showTableData(id);
        }
    }//GEN-LAST:event_jButton_log_fileActionPerformed

    private void jButton_kont_infaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kont_infaActionPerformed
        // TODO add your handling code here:
        konts_infa k = new konts_infa(this);
        String id = jTextField_id_add.getText();
        if(id.equals("")){ 
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs!");
        }else{
            k.setVisible(true);
            setVisible(false);
            Connections_database con = new Connections_database();
            k.showTableData(id);
        }
    }//GEN-LAST:event_jButton_kont_infaActionPerformed

    private void jButton_add_credit_kontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_credit_kontActionPerformed
        // TODO add your handling code here:
        String id = jTextField_id_add.getText();
        
        Konti k1 = new Konti();
        if(id.equals("")){ 
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs!");
        }else{
            String number = null;
            String condition = "kredita";
            String number1 =k1.create_kont_number(number);
            System.out.println(number1);
            if(k1.check_Information_about_cont(id, condition)){
                JOptionPane.showMessageDialog(null, "Lietotajam ar "+id+" jau ir tada konta tips!");
            }else{
                Random rand = new Random();
                String timeStamp = null;
                String apraksts = null;
                int summa = rand.nextInt(10000) + 1;
                System.out.println(summa);
                Integer.toString(summa);
                JOptionPane.showMessageDialog(null, "Konts tika izveidots!");
                k1.create_credit_kont(id, number1, summa);
                timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                apraksts = "Lietotajs ar id: "+id+" izveidoja kredita kontu: "+timeStamp;
                k1.log_konti(id, apraksts);
            }
        }
        
    }//GEN-LAST:event_jButton_add_credit_kontActionPerformed

    private void jButton_add_noguldijuma_kontsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_noguldijuma_kontsActionPerformed
        // TODO add your handling code here:
        Konti k1 = new Konti();
        String id = jTextField_id_add.getText();
        if(id.equals("")){ 
            JOptionPane.showMessageDialog(null, "Nav izvelets lietotajs!");
        }else{
            String number = null;
            String condition = "Noguldijuma";
            String number1 =k1.create_kont_number(number);
            System.out.println(number1);
            if(k1.check_Information_about_cont(id, condition)){
                JOptionPane.showMessageDialog(null, "Lietotajam ar "+id+" jau ir tada konta tips!");
            }else{
                int summa= 0;
                String timeStamp = null;
                String apraksts = null;
                Integer.toString(summa);
                System.out.println(summa);
                JOptionPane.showMessageDialog(null, "Konts tika izveidots!");
                k1.create_nakop_kont(id, number1,summa);   
                timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                apraksts = "Lietotajs ar id: "+id+" izveidoja noguldijuma kontu: "+timeStamp;
                k1.log_konti(id, apraksts);
                
            }
        }
        
    }//GEN-LAST:event_jButton_add_noguldijuma_kontsActionPerformed

    private void jButton_statistic_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_statistic_showActionPerformed
        // TODO add your handling code here:
        statistic_show stata = new statistic_show(this);
        stata.setVisible(true);
        setVisible(false);
        Connections_database con = new Connections_database();
        stata.statistic_show_user();
        stata.statistic_show_admin();
        stata.statistic_show_kont();
    }//GEN-LAST:event_jButton_statistic_showActionPerformed
    
    public void showTableData(){
        try{
            con = Connections_database.getConnection();
            String  sql= "SELECT ID,Vards,Uzvards,E_pasts,Parole FROM `useri` WHERE Conditions = 'User'";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nekas nav!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_credit_kont;
    private javax.swing.JButton jButton_add_noguldijuma_konts;
    private javax.swing.JButton jButton_add_user;
    private javax.swing.JButton jButton_delete_user;
    private javax.swing.JButton jButton_kont_infa;
    private javax.swing.JButton jButton_log_file;
    private javax.swing.JButton jButton_statistic_show;
    private javax.swing.JButton jButton_update_user;
    private javax.swing.JButton jButtonexit_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_email_add;
    private javax.swing.JTextField jTextField_id_add;
    private javax.swing.JTextField jTextField_name_add;
    private javax.swing.JTextField jTextField_pass_add;
    private javax.swing.JTextField jTextField_surname_add;
    // End of variables declaration//GEN-END:variables
}
