/**
 *
 * @author 62dnkurilovics
 */
//prieks datubazes savienosanas un darbam
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
//Prieks panelu izvadisanam un citam
import javax.swing.JOptionPane;

public class Login_page extends javax.swing.JFrame {
    Connection con;
    Main_menu menu  = null;
    Admin_page ad = null;
    PreparedStatement pst;
    ResultSet rs;
    User_page us = null;
    Admin admin;
    /**
     * Creates new form Login_page
     */
    
    public Login_page(Main_menu menu) {
      initComponents() ;
      this.menu = menu;
      this.setLocationRelativeTo(null);
    }
    public Login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonentry_login = new javax.swing.JButton();
        jTextField_id_login = new javax.swing.JTextField();
        jPasswordField_login = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_login = new javax.swing.JComboBox<>();
        jButtoncancel_login = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Login Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Parole");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        jButtonentry_login.setBackground(new java.awt.Color(51, 102, 255));
        jButtonentry_login.setForeground(new java.awt.Color(255, 255, 255));
        jButtonentry_login.setText("Ielogoties");
        jButtonentry_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonentry_loginActionPerformed(evt);
            }
        });

        jPasswordField_login.setText("jPasswordField1");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Izveleties lietotaju");

        jComboBox_login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox_login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "User" }));
        jComboBox_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_loginActionPerformed(evt);
            }
        });

        jButtoncancel_login.setBackground(new java.awt.Color(242, 38, 19));
        jButtoncancel_login.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncancel_login.setText("Atcelt");
        jButtoncancel_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancel_loginActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Paradit paroli");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_login, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField_login, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addComponent(jTextField_id_login, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonentry_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoncancel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_id_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_login, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_login, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonentry_login)
                    .addComponent(jButtoncancel_login))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonentry_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonentry_loginActionPerformed
        // ieesanas apstiprinasana
        String id = jTextField_id_login.getText();
        String pword = jPasswordField_login.getText();
        String option = jComboBox_login.getSelectedItem().toString();
        
        if(id.equals("") || pword.equals("") || option.equals("Select")){
            JOptionPane.showMessageDialog(null, "Jus neaizpildijat kaut kadu autorizesanas lauku!");
        }else{
            try{
                con = Connections_database.getConnection();
                pst = con.prepareStatement("select *from useri where ID=? and Parole=?");
                pst.setString(1, id);
                pst.setString(2, pword);
                rs = pst.executeQuery();
                
                if(rs.next()){
                  int reizes = 0;
                  String s1 = rs.getString("Conditions");
                  String un = rs.getString("ID");
                  String un1 = rs.getString("Vards");
                   String timeStamp = null;
                  if(option.equalsIgnoreCase("Admin") && s1.equalsIgnoreCase("Admin")){
                      Admin_page ad = new Admin_page(un,un1,menu);
                      ad.setVisible(true);
                      setVisible(false);
                      reizes =1;
                      timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                      String apraksts = "Admins ar id: "+id+" iegaja sistema: "+timeStamp;
                      con = Connections_database.getConnection();
                      java.sql.PreparedStatement stmt = con.prepareStatement(
                      "INSERT INTO `log_file`(`ID`, `Apraksts`) VALUES (?,?)");
                      stmt.setString(1, id);
                      stmt.setString(2, apraksts);
                      stmt.executeUpdate();
                  }
                                       
                  if(option.equalsIgnoreCase("User") && s1.equalsIgnoreCase("User")){
                      String un2 = rs.getString("ID");
                      String un3 = rs.getString("Vards");
                      User_page us = new User_page(un2,menu,un3);
                      us.setVisible(true);
                      setVisible(false);
                      reizes = 1;
                      timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                      String apraksts = "Lietotajs ar id: "+id+" iegaja sava kabineta: "+timeStamp;
                      con = Connections_database.getConnection();
                      java.sql.PreparedStatement stmt = con.prepareStatement(
                      "INSERT INTO `log_file`(`ID`,`Apraksts`) VALUES (?,?)");
                      stmt.setString(1, id);
                      stmt.setString(2, apraksts);
                      stmt.executeUpdate();
                      us.showTableData(id);
                  }
                  if(reizes ==0)
                      JOptionPane.showMessageDialog(null, "Nepareizi izvelets Lietotaja veids!", "Failure", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Nepareizs id vai parole!", "Failure", JOptionPane.ERROR_MESSAGE);
                    jTextField_id_login.setText("");
                    jPasswordField_login.setText("");   
                }
            }catch(Exception ex){
                 System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_jButtonentry_loginActionPerformed

    private void jButtoncancel_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancel_loginActionPerformed
        //izisana no ieesanas
        setVisible(false);
        if (menu != null)
        menu.setVisible(true);
    }//GEN-LAST:event_jButtoncancel_loginActionPerformed

    private void jComboBox_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_loginActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jPasswordField_login.setEchoChar((char)0);
        }else{
            jPasswordField_login.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncancel_login;
    public javax.swing.JButton jButtonentry_login;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_login;
    public javax.swing.JTextField jTextField_id_login;
    // End of variables declaration//GEN-END:variables
}
