

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kuric
 */
public class User_page extends javax.swing.JFrame {
Main_menu menu = null;
    Admin_page admin1;
    Connection con;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Konti k1;
    /**
     * Creates new form User_page
     */
    public User_page() {
        initComponents();
    }
    
    public User_page(String id, Main_menu menu,String Vards) {
        initComponents();
        this.menu = menu;
        this.setLocationRelativeTo(null);
        jLabel1.setText("Labdien dargais lietotajs "+Vards+", id= ");
        jLabel2.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_exit_user = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_money = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_add_money = new javax.swing.JButton();
        jTextField_kont_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_remove_money = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_add_money_other = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_transfer_money = new javax.swing.JButton();
        jTextField_kont_add_other = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton_exit_user.setBackground(new java.awt.Color(255, 51, 0));
        jButton_exit_user.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_exit_user.setForeground(new java.awt.Color(240, 240, 240));
        jButton_exit_user.setText("Iziet");
        jButton_exit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit_userActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Naudas daudzums:");

        jButton_add_money.setBackground(new java.awt.Color(51, 204, 0));
        jButton_add_money.setForeground(new java.awt.Color(240, 240, 240));
        jButton_add_money.setText("Ielikt naudu ");
        jButton_add_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_moneyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Konta numurs:");

        jButton_remove_money.setBackground(new java.awt.Color(255, 102, 0));
        jButton_remove_money.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_remove_money.setForeground(new java.awt.Color(240, 240, 240));
        jButton_remove_money.setText("Iznemt naudu");
        jButton_remove_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove_moneyActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Visas tiesibas aizsargatas 2018");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankimage/swedbank.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Naudas summa:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Konts: ");

        jButton_transfer_money.setBackground(new java.awt.Color(51, 153, 0));
        jButton_transfer_money.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_transfer_money.setForeground(new java.awt.Color(240, 240, 240));
        jButton_transfer_money.setText("Parskaitit naudu");
        jButton_transfer_money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transfer_moneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jButton_add_money)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_kont_number, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_money, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_remove_money))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_add_money_other)
                            .addComponent(jTextField_kont_add_other)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_transfer_money)
                        .addGap(39, 39, 39)
                        .addComponent(jButton_exit_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_kont_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_add_money_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField_kont_add_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_remove_money)
                    .addComponent(jButton_add_money)
                    .addComponent(jButton_exit_user)
                    .addComponent(jButton_transfer_money))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_exit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit_userActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        if (menu != null)
        menu.setVisible(true);
         try{
                String id =jLabel2.getText();
                String timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                String apraksts = "Lietotajs ar id: "+id+" izgaja no sava kabineta: "+timeStamp;
                con = Connections_database.getConnection();
                java.sql.PreparedStatement stmt = con.prepareStatement(
                "INSERT INTO `log_file`(`ID`, `Apraksts`) VALUES (?,?)");
                stmt.setInt(1,Integer.parseInt(id));
                stmt.setString(2, apraksts);
                stmt.executeUpdate();
            }catch(Exception ex){
                System.out.println(""+ex);
            }
    }//GEN-LAST:event_jButton_exit_userActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow(); 
        TableModel model=jTable1.getModel(); 
        jTextField_kont_number.setText(model.getValueAt(i,2).toString());
        jLabel7.setText(model.getValueAt(i,1).toString()); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_add_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_moneyActionPerformed
        // TODO add your handling code here:
        Konti k1 = new Konti();
        String money =jTextField_money.getText();
        String id =jLabel2.getText();
        int money1 = Integer.parseInt(money);
        String condition = jLabel7.getText();
        String number = jTextField_kont_number.getText();
        System.out.println(condition);
        if(money1<=0){
            JOptionPane.showMessageDialog(null, "Nepielaujamais naudas daudzums!", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
            int summa = 0;
            int kopa = 0;
            int summa1 = k1.GetKonti(number, condition, summa);
            System.out.println("Naudas summa uz jusu konta tagad: "+summa1);
            if(condition.equals("Noguldijuma")){
                kopa = (int) (summa1+money1+(money1*0.05));
                System.out.println(kopa);
            }else{
                kopa = summa1+money1;
            }
            k1.update_Kont(number, condition, kopa);
            System.out.println("Naudas summa uz jusu konta pec parskaitisanas: "+kopa);
            JOptionPane.showMessageDialog(null, "Nauda ir parskaitita!"); 
            String timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
            String apraksts = "Lietotajs ar id: "+id+" ielika: "+kopa+" summu sava "+condition+" konta: "+number+" "+timeStamp; 
            k1.log_konti(id, apraksts);
            showTableData(id);
        }
    }//GEN-LAST:event_jButton_add_moneyActionPerformed

    private void jButton_remove_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove_moneyActionPerformed
        // TODO add your handling code here:
        String money =jTextField_money.getText();
        String id =jLabel2.getText();
        Konti k1 = new Konti();
        int money1 = Integer.parseInt(money);
        String condition = jLabel7.getText();
        String number = jTextField_kont_number.getText();
        System.out.println(condition);
        if(money1<=0){
            JOptionPane.showMessageDialog(null, "Nepielaujamais naudas daudzums!", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
            int summa = 0;
            int kopa = 0;
            int summa1 = k1.GetKonti(number, condition, summa);
            System.out.println("Naudas summa uz jusu konta tagad: "+summa1);
            if(condition.equals("Kredita")){
                kopa = (int) (summa1-money1-(money1*0.05));
                System.out.println(kopa);
            }else{
                kopa = summa1-money1;
            }
            if(kopa<0){
                JOptionPane.showMessageDialog(null, "Nepietiek lidzeklu naudas iznemsanai!", "Failure", JOptionPane.ERROR_MESSAGE);
            }else{
                k1.update_Kont(number, condition, kopa);
                System.out.println("Naudas summa uz jusu konta pec parskaitisanas: "+kopa);
                JOptionPane.showMessageDialog(null, "Nauda ir iznemta!");
                String timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                String apraksts = "Lietotajs ar id: "+id+" iznema: "+kopa+" summu no sava "+condition+" konta: "+number+" "+timeStamp; 
                k1.log_konti(id, apraksts);
                showTableData(id);
            }
        }
    }//GEN-LAST:event_jButton_remove_moneyActionPerformed

    private void jButton_transfer_moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transfer_moneyActionPerformed
        // TODO add your handling code here:
        String money =jTextField_add_money_other.getText();
        String id =jLabel2.getText();
        Konti k1 = new Konti();
        int money1 = Integer.parseInt(money);
        String condition = jLabel7.getText();
        String number = jTextField_kont_number.getText();
        String number1 = jTextField_kont_add_other.getText();
        System.out.println(condition);
        if(money1<=0){
            JOptionPane.showMessageDialog(null, "Nepielaujamais naudas daudzums!", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
           int summa = 0;
            int kopa = 0;
            int summa1 = k1.GetKonti(number, condition, summa);
            System.out.println("Naudas summa uz jusu konta tagad: "+summa1);
            if(condition.equals("Kredita")){
                kopa = (int) (summa1-money1-(money1*0.05));
                System.out.println(kopa);
            }else{
                kopa = summa1-money1;
            }
            if(kopa<0){
                JOptionPane.showMessageDialog(null, "Nepietiek lidzeklu naudas iznemsanai!", "Failure", JOptionPane.ERROR_MESSAGE);
            }else{
                if(k1.check_kont(number1)){
                    k1.update_Kont(number, condition, kopa);
                    System.out.println("Viss ir ok");
                    int summa2 = 0;
                    int summa3 = k1.GetKonti2(number1, summa2);            
                    int kopa1 = summa3+money1;
                    System.out.println(kopa1);
                    k1.update_Kont2(number1, kopa1);
                    JOptionPane.showMessageDialog(null, "Nauda ir parskaitita!");
                    String timeStamp = new SimpleDateFormat("dd-M-yyyy hh:mm:ss").format(Calendar.getInstance().getTime());
                    String apraksts = "Lietotajs ar id: "+id+" parskaitija: "+kopa+" summu no sava "+condition+" konta: "+number+"uz kontu: "+number1+" "+timeStamp; 
                    k1.log_konti(id, apraksts);
                    showTableData(id);
                }else{
                    JOptionPane.showMessageDialog(null, "Tads konts neeksiste!", "Failure", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton_transfer_moneyActionPerformed
    
    public void showTableData(String id){
        try{
            con = Connections_database.getConnection();
            String  sql= "SELECT *FROM `konti` WHERE ID="+id;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nekas nav!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_money;
    private javax.swing.JButton jButton_exit_user;
    private javax.swing.JButton jButton_remove_money;
    private javax.swing.JButton jButton_transfer_money;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_add_money_other;
    private javax.swing.JTextField jTextField_kont_add_other;
    private javax.swing.JTextField jTextField_kont_number;
    private javax.swing.JTextField jTextField_money;
    // End of variables declaration//GEN-END:variables
}
